### ISSUE TITLE
Switchable forbidden area

### ISSUE THREAD

**Issue by jonathanleinola** [zach-goh/Omron_AMR_ROS2#1]
Hi,

Do you have any idea/ideas on how could I utilize this package for switchable forbidden areas? For eg., if something is at location x,y then switch the forbidden area on. I posted the same question to the Omron ros1 package as well. 

Kindly,
Jonathan

**Comment by CFZeon** [comment]
Hi Jonathan, 

The switchable forbidden areas can be controlled by ARCL commands. Please check goto_goal.py found in om_aiv_navigation for an example on how to create an action client.

According to page 185 of Mobile Robot Software Suite User's Guide, there are 4 tasks that you can use to turn a Switchable Forbidden Line or Area on or off:
switchForbiddenOff
switchForbiddenOn
switchForbiddenOffByPrefix
switchForbiddenOnByPrefix

In this case, your ARCL command would look something like "dotask switchForbiddenOff" 
In code, it should be implemented like this in line 21 of goto_goal.py
goal.command = "dotask switchForbiddenOff"

I hope this helps.

Regards,
Zeon

**Comment by jonathanleinola** [comment]
Hi Zeon,

Thanks for the answer. I'll try that; I think the switchForbiddenOff / switchForbiddenOn is the command and then you would need a name parameter for the exact area to be switched on/off? 

Kindly,
Jonathan

**Comment by jonathanleinola** [comment]
Also, do you think there is a difference between the switchableForbiddenArea and the ForbiddenArea? I was just curious that how/could i extract the positional information from it somehow?

**Comment by CFZeon** [comment]
Hi Jonathan,

I have personally never used switchable forbidden areas. However, I would presume that switchForbiddenOffByPrefix would allow you to choose a specific one to switch off though I am unsure if it takes in a number or a name.

As for normal forbidden areas, you can obtain the positional information from the .map file that you acquire from mobile planner. In https://github.com/zach-goh/Omron_AMR_ROS2/blob/master/src/amr_visualisation/map/data.map from lines 2315 to 2317.

You can interpret the information by referring to section 4.2 in the developer's guide here: https://github.com/zach-goh/Omron_AMR_ROS2/blob/master/docs/DeveloperGuide.adoc

Regards,
Zeon

**Comment by jonathanleinola** [comment]
Thanks CFZeon! I'll try that. Just came to my mind that there seems to be the dynamic obstacle functionality (lines 503-520) in the .map file. Any idea if it would be possible to inject that data from another source into the robot?

**Comment by CFZeon** [comment]
Hi Jonathan,

I have asked around and it seems like those are just configuration settings on how the robot responds to dynamic obstacles. They don't actually mean dynamic obstacle data, which should not be on a map file.

Regards,
Zeon

Regards,
Zeon

**Comment by jonathanleinola** [comment]
Hi Zeon,
Okay. That makes sense since there seems not to be a location value for the dynamic obstacle. It's a pity though, would be nice to find a way to externally output location data to the robot.

Kindly,
Jonathan
