### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by jaycho112** [zach-goh/Omron_AMR_ROS2#2]
hello
First of all, I do appreciate for your project

I have modified main_param.yaml like this

LD robot related params
ip_address: "1.2.3.4"
def_arcl_passwd: "adept"

#local machine related params
local_ip: "1.2.3.5"
local _port: 7179

I want to connect ld-250 with my jetson board by direct wlan connection using this socket
but as I launch '1robot.launch' file, It stops and doesn't connect well

Can you get me a litte help plz??

Looking forward to wait for your reply thankx.

**Comment by jaycho112** [comment]
Thanks for your reply!
I'm integrating Nvidia Jetson Nano with Omron LD-250 with Omron korea
running on Ubuntu 18.04, jetpack4.6, ros melodic with "Omron_LD_ROS_Package"(version1 of your package)
I have connected wlan to ld-250 user wlan port by using default ip address(local : 192.168.1.10 & host : 192.168.1.50)
Here is my screenshot of my terminal that I launched '1robot.launch'
I'm confusing that It stops at 'Listening to new socet on xxx.xxx.x.xx at port xxxxx'
Is this normal that the terminal dosen't present any word about ARCL? ( as I launch display.launch, I think jetson nano successfully connected to ld-250, It shows the radar points on the rviz map)

or Can you get me some explain about 1robot.launch file that how it works? Thank you very much
![Screenshot from 2021-09-09 09-32-58](https://user-images.githubusercontent.com/88361755/132603840-949fd048-9b99-4c6b-ab4d-1086b48cd5cd.png)

**Comment by CFZeon** [comment]
Hi Jaycho, 

I did not work on the ROS1 repo and I'm not too sure of how it works, however I looked into it and it seems that the ARCL server is already up and running on your end. Did you try running the goto_goal demo? From experience, usually if you can see the laser pointer then it means that you have set everything up correctly. You might want to run the demo just to check if the ARCL is working as it should.

As for how 1robot works, it launches 3 nodes,
arcl_api_server.py
action_servers.py
ld_states_publisher.py

The ARCL api server is made to allow the ros machine to communicate with the robot through ARCL, and the action_server is an interface that is made for you to easily interface with it through action clients. The ld_states_publisher publishes information such as its current position.

Please try it out and tell me how it works. The help I can offer is limited if you're not using this repo however.

Regards,
Zeon

**Comment by jaycho112** [comment]
sorry for being late. 

first of all, big thx for your reply

actually I've succeed with connect to ld-250 with your awesome code...

now I'm creating an simple running shell script GUI for use this app more easily... let me announce u when I finished my project.. Thx

**Comment by CFZeon** [comment]
Glad to hear that! I'll be closing this issue now since your problem is solved.
